steps:
  # Step 1: Build the JAR file
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: './'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/demopocs/autozone-bc/springbackend:$COMMIT_SHA', 
      '.'
    ]

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/demopocs/autozone-bc/springbackend:$COMMIT_SHA'
    ]

images:
  - 'us-central1-docker.pkg.dev/demopocs/autozone-bc/springbackend:$COMMIT_SHA'

substitutions:
  _PROJECT_ID: 'demopocs'
