steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'package', '-DskipTests']
  id: 'Build JAR'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/demopocs/autozone/springbackend:$COMMIT_SHA', '.']
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/demopocs/autozone/springbackend:$COMMIT_SHA']
  id: 'Push Docker Image'

images:
- 'us-central1-docker.pkg.dev/demopocs/autozone/springbackend:$COMMIT_SHA'
