options:
  logging: CLOUD_LOGGING_ONLY  # Store logs in Cloud Logging

steps:
  # Step 1: Setup JDK and Build Spring Boot App
  - id: 'Build JAR'
    name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests', '-X']
    dir: "autozone-spring-poc/autozonepoc"  # Make sure Maven runs from the root of the workspace (default in Cloud Build)
    # Ensure we are in the correct directory to find the pom.xml

  # Step 2: Build Docker Image
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA',
      '.'  # The build context is the current directory
    ]

  # Step 3: Push Docker Image to Artifact Registry
  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
    ]

# Define Substitutions
substitutions:
  _PROJECT_ID: 'demopocs'
  _REPO_NAME: 'autozone-bc'  # Adjust repo name for the artifact registry
  _IMAGE_NAME: 'springbackend'  # Define image name as springbackend
